### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by 32ruHasegawa** [32ruHasegawa/chat_space#9]
#IPアドレス
18.180.209.23

**Comment by yasunamiura** [comment]
長谷川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①サイドバーにあるグループ名と最新メッセージの下線を消しましょう
<img width="291" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/80662561-86ef1b80-8acc-11ea-87ae-e280858a553c.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
